### ISSUE TITLE
Premature end of stream, needed 4 more bytes

### ISSUE THREAD

**Issue by matzrm** [Maaaartin/adb-ts#5]
I'm tryng to use adb-ts, but I'm getting this error:
`Premature end of stream, needed 4 more bytes`

My code is this:

```
const adb = new Client({
                bin: '/usr/bin/adb',
                port: 5037,
                host: '127.0.0.1'
            });
const s = await adb.connect('127.0.0.1',device_port);
const buffer = await adb.screenshot(s);
await adb.disconnect(s);
reply.send(buffer);
```

I'm getting this error both on debug (Windows) and also on deploy server (debian)

Anyone can help?

**Comment by matzrm** [comment]
If I try to put a breakpoint on client.js line 125 and I go with step by step with run fuction, the code runs good, but without a breakpoint I obtain the error!

**Comment by Maaaartin** [comment]
@matzrm should be fixed in version `4.0.3`. However the code snippet you mentioned would not work anyway. 
First of all you do not need to connect to the device over local network, to get a screenshot buffer from connected device (over usb), use code like this:

```
   const adb = new Client();
   const buffer = await adb.screenshot('<device_serial>');
```
Alternatively you `listDevices` to get serial (id) of connected devices:
```
    const adb = new Client();
    const [device] = await adb.listDevices();
    const buffer = await adb.screenshot(device.id);
```
If you need to connect to the device over local network, you must pass `device serial` as parameter of `connect()`, before that you (might) need to call `tcpip()` as well. To get the ip address, you can use `getIpAddress()` method. So the code would look like this:
```
    const adb = new Client();
    await adb.tcpip('device_serial');
    const s = await adb.connect('<ip_address>');
    const buffer = await adb.screenshot(s);
    await adb.disconnect(s);
```
Check documentation for above mentioned methods 
https://maaaartin.github.io/adb-ts/classes/Client.Client.html#connect
https://maaaartin.github.io/adb-ts/classes/Client.Client.html#getIpAddress

**Comment by matzrm** [comment]
Dear @Maaaartin,

thank you, `4.0.3` fixed my issue.

All my android devices are remoted connected to my server  forwarding the port 5555 through ssh, so thank you also for this code:

```
    const adb = new Client();
    await adb.tcpip('device_serial');
    const s = await adb.connect('<ip_address>');
    const buffer = await adb.screenshot(s);
    await adb.disconnect(s);
```

Best regards

**Comment by matzrm** [comment]
Just one thing, If I call `  await adb.tcpip('device_serial');` before ` await adb.connect('<ip_address>');` I obtain device not found

**Comment by Maaaartin** [comment]
> Just one thing, If I call ` await adb.tcpip('device_serial');` before ` await adb.connect('<ip_address>');` I obtain device not found

No problem. Can you paste your code snippet pls?

**Comment by matzrm** [comment]
The code is yours:

```
  const adb = new Client();
    await adb.tcpip('127.0.0.1:12345');
    const s = await adb.connect('127.0.0.1',12345);
    const buffer = await adb.screenshot(s);
    await adb.disconnect(s);
```


Without `adb.tcpip(...)` the code works like a charm!

**Comment by Maaaartin** [comment]
I see, thats weird, usually one must do `tcpip()` to be able to connect. Try adding `   await adb.waitFor('usb', 'device');` below `tcpip()`, I thought this call is not necesarry, but perhaps it is. The code worked for me, the behaviour might also be influenced by adb version and android version of the device.

**Comment by matzrm** [comment]
If I use `await adb.waitFor('usb', 'device');` the system waits for a usb device that I have not. And also if I put this code after `adb.tcpip()` it's never executed because` tcpip(`) throws "no device error".

Are you sure you are not testing ` await adb.tcpip('127.0.0.1:12345');` with a already connected device? Because in this way this function works.

**Comment by Maaaartin** [comment]
I think I understand now, you need to call `await adb.tcpip(device.id);` only when the device have not been connected over wifi before. After that, even after disconnection, you should be able to connect to the device without setting it to tcpip again.

I assume you are probably getting `No device found` error because you try to execute it on a device what has been disconnected. Or you are calling `adb.tcpip('127.0.0.1:12345')` with ipv4 as a parameter, which I am not sure if that works, it expects the device `serial` (in other words, connection over usb), but I am not 100 % sure.

I hope it makes sense. Reopen if you get any other errors regarding this issue. :)

**Comment by matzrm** [comment]
Hi @Maaaartin , just for clarify that I'm starting from a device that has tcpip already enabled, because mine is not a device for end-user but a kiosk and so many producer add this option in the device settings.

So I understand only now what's your point of start and because I not need to call adb.tcpip!

So thank you for help me!
